# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy_streamer.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'proxy_streamer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proxy_streamer.proto\x12\x0eproxy_streamer\"\x0f\n\rStreamRequest\"\x1e\n\x0eStreamResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2]\n\rProxyStreamer\x12L\n\tGetStream\x12\x1d.proxy_streamer.StreamRequest\x1a\x1e.proxy_streamer.StreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_streamer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMREQUEST']._serialized_start=40
  _globals['_STREAMREQUEST']._serialized_end=55
  _globals['_STREAMRESPONSE']._serialized_start=57
  _globals['_STREAMRESPONSE']._serialized_end=87
  _globals['_PROXYSTREAMER']._serialized_start=89
  _globals['_PROXYSTREAMER']._serialized_end=182
# @@protoc_insertion_point(module_scope)
